---
# file: hardened/tasks/main.yml

# Disable the root account
- name: disable root
  command: usermod -p '*' root
  tags: users

# Ensure sudo needs a password
- name: force password with sudo
  lineinfile: dest=/etc/sudoers
              regexp="^\%sudo\s*ALL\=\(ALL\:ALL\)\s*NOPASSWD\:\s*ALL"
              line="%sudo ALL=(ALL:ALL) ALL"
              state=present
  tags: users

# Import tasks for ssh hardening
- include: ssh.yml

# Enable Google Auth 2FA
- include: google-auth.yml
  when: "{{ enable_2fa|default(true)|bool }}"

# Install `cracklib` to improve password security
- name: install cracklib
  apt: name=libpam-cracklib state=installed
