---
# file: hardened/tasks/main.yml

# Disable the root account
- name: disable root
  command: usermod -p '*' root
  tags: users

# Ensure sudo needs a password
- name: force password with sudo
  lineinfile:
    dest: /etc/sudoers
    regexp: ^\%sudo\s*ALL\=\(ALL\:ALL\)\s*NOPASSWD\:\s*ALL
    line: "%sudo ALL=(ALL:ALL) ALL"
    state: present
  tags: users

# Import tasks for ssh hardening
- include: ssh.yml

# Enable Google Auth 2FA
- include: google-auth.yml
  when: "{{ enable_2fa|default(true)|bool }}"

# Install `cracklib` to improve password security
- name: install cracklib
  apt: name=libpam-cracklib state=installed

- name: modify security settings for passwords
  lineinfile:
    dest: /etc/pam.d/common-password
    regexp: ^password\s*requisite\s*pam_cracklib.*$
    line: "password        requisite                       pam_cracklib.so retry=3 minlen=15 difok=5 ucredit=-1 lcredit=-2 dcredit=-1 ocredit=-1"

# Setup Monit for IDS
# - include: monit.yml
