---
# file: roles/base/vars/main.yml

local_deploy_path: deploy

ubuntu_common_required_packages:
  - ufw
  - fail2ban
  - unattended-upgrades
  - logwatch
  - software-properties-common
  - python2.7
  - python-apt

ubuntu_common_optional_packages:
  - python
  - python-dev
  - git
  - p7zip-full
  - unzip
  - ntp
  - nfs-common
  - screen

ubuntu_common_ssh_port: 22222

ubuntu_common_deploy_user_name: adminlocal

ubuntu_common_logwatch_email: myemailaddress@dot.com

# this will be used as the `adminlocal` key. Configure as a path
default_ssh_key: ansible.id_rsa

# only these users will have SSH access to the server
ssh_users:
    - name: "{{ ubuntu_common_deploy_user_name }}"

# can add additional users here if needed
users:
  - "{{ ssh_users }}"
